const assert = require('node:assert/strict')
const { mkdirSync, writeFileSync, existsSync, readFileSync } = require('node:fs')
const { resolve } = require('node:path')
const { chromium } = require('playwright-core')
const AxeBuilder = require('@axe-core/playwright').default
const { browserOptions } = require('./browser.cjs')
const base = process.env.APP_URL || 'http://localhost:5173'
const out = resolve(__dirname, '../artifacts/booking-audit')
mkdirSync(out, { recursive: true })
const report = process.env.AUDIT_RESUME && existsSync(resolve(out, 'report.json')) ? JSON.parse(readFileSync(resolve(out, 'report.json'))) : { screens: [], errors: [], checks: [] }
async function request(path, body, token, method = 'POST') {
  const response = await fetch(`http://localhost:5000/api${path}`, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) })
  const payload = await response.json()
  assert.ok(response.ok, `${path}: ${payload.error}`)
  return payload.data
}
async function capture(page, name) {
  for (const theme of ['light', 'dark']) for (const width of [1440, 1024, 768, 390, 320]) {
    const previous = report.screens.find(s => s.name === name && s.theme === theme && s.width === width)
    if (process.env.AUDIT_RESUME && previous && previous.overflow <= 0 && !previous.violations.length) continue
    report.screens = report.screens.filter(s => !(s.name === name && s.theme === theme && s.width === width))
    await page.setViewportSize({ width, height: 900 })
    await page.evaluate(theme => { document.documentElement.dataset.theme = theme }, theme)
    await page.waitForTimeout(750)
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)
    const violations = (await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => ({ target: n.target, summary: n.failureSummary })) }))
    const file = `${name}-${theme}-${width}.png`
    await page.screenshot({ path: resolve(out, file), fullPage: true, animations: 'disabled', timeout: 60000 })
    report.screens.push({ name, theme, width, overflow, violations, file })
    writeFileSync(resolve(out, 'report.json'), JSON.stringify(report, null, 2))
    console.log(`${name} ${theme} ${width}: overflow=${overflow}, axe=${violations.length}`)
  }
  await page.setViewportSize({ width: 1440, height: 900 })
}
async function main() {
  const health = await request('/health', null, null, 'GET')
  assert.equal(health.databaseMode, 'memory', 'This audit creates bookings: memory database required')
  const browser = await chromium.launch(browserOptions())
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, timezoneId: 'Asia/Dhaka' })
    const page = await context.newPage()
    page.on('pageerror', e => report.errors.push(e.message))
    await page.goto(`${base}/?intro=0`, { waitUntil: 'networkidle' })
    await page.getByPlaceholder('From where?').fill('Chattogram')
    await page.getByRole('option', { name: 'Chattogram', exact: true }).click()
    await page.getByPlaceholder('To where?').fill('Dhaka')
    await page.getByRole('option', { name: 'Dhaka', exact: true }).click()
    await page.getByRole('button', { name: 'Search trains', exact: true }).click()
    await page.locator('.journey-card').first().waitFor()
    await capture(page, 'results-loaded')
    await page.getByRole('button', { name: /Stops and journey details/ }).first().click()
    await page.getByRole('dialog').waitFor()
    await capture(page, 'journey-drawer')
    await page.keyboard.press('Escape')
    await page.locator('.journey-card .fare-tile:not([disabled])').first().click()
    await page.locator('.seat:not([disabled])').first().waitFor()
    await page.locator('.seat:not([disabled])').first().focus()
    await page.keyboard.press('ArrowRight')
    await page.keyboard.press('Space')
    assert.equal(await page.locator('.seat[aria-pressed="true"]').count(), 1)
    report.checks.push('Seat arrow key navigation and Space selection')
    await capture(page, 'seats-selected')
    await page.getByRole('button', { name: 'Continue to passengers', exact: true }).click()
    await page.getByRole('button', { name: 'Hold seats and continue', exact: true }).click()
    await capture(page, 'passenger-errors')
    await page.getByLabel('Full name', { exact: true }).fill('Audit Passenger')
    await page.getByLabel('Age', { exact: true }).fill('28')
    await page.getByRole('button', { name: 'Hold seats and continue', exact: true }).click()
    await page.getByRole('tab', { name: 'Create account' }).click()
    const id = Date.now()
    await page.getByPlaceholder('Your full name').fill('Audit Passenger')
    await page.getByPlaceholder('you@example.com').fill(`audit.${id}@ferrovia.local`)
    await page.locator('input[name="password"]').fill('Audit123!')
    await page.locator('.auth-form button[type=submit]').click()
    await page.getByRole('heading', { name: 'Review and pay' }).waitFor()
    report.checks.push('Mid-booking registration resumes to payment')
    for (const method of ['Mobile Banking', 'Card', 'Bank Transfer']) {
      await page.locator('.pay-method').filter({ hasText: method }).click()
      await capture(page, `payment-${method.replaceAll(' ', '-').toLowerCase()}`)
    }
    await page.getByPlaceholder('Transfer reference number').fill(`AUDIT-${id}`)
    await page.getByRole('button', { name: /^Pay / }).click()
    await page.getByRole('heading', { name: /booked/ }).waitFor()
    await capture(page, 'confirmation')
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name: /Download/ }).click()
    await (await download).saveAs(resolve(out, 'ticket.txt'))
    await page.emulateMedia({ media: 'print' })
    await page.pdf({ path: resolve(out, 'confirmation.pdf'), format: 'A4', printBackground: true })
    await page.emulateMedia({ media: 'screen' })
    report.checks.push('Ticket text download and print PDF')
    const passenger = await page.evaluate(() => ({ token: localStorage.getItem('rail-token'), user: JSON.parse(localStorage.getItem('rail-user')) }))
    await page.goto(`${base}/?intro=0#/tickets`, { waitUntil: 'networkidle' })
    await page.getByRole('tab', { name: /Upcoming/ }).waitFor()
    await capture(page, 'tickets-upcoming')
    const calendar = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Add to calendar' }).click()
    await (await calendar).saveAs(resolve(out, 'journey.ics'))
    await page.getByRole('button', { name: 'View', exact: true }).click()
    await capture(page, 'ticket-dialog')
    await page.emulateMedia({ media: 'print' })
    assert.equal(await page.locator('.page-header').isVisible(), false)
    await page.pdf({ path: resolve(out, 'ticket-dialog.pdf'), format: 'A4', printBackground: true })
    await page.emulateMedia({ media: 'screen' })
    await page.keyboard.press('Escape')
    await page.goto(`${base}/?intro=0#/dashboard`, { waitUntil: 'networkidle' })
    await capture(page, 'dashboard-upcoming')
    await page.goto(`${base}/?intro=0#/tickets`, { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await capture(page, 'cancel-dialog')
    await page.getByRole('dialog').getByRole('button', { name: /Request cancellation/ }).click()
    await page.getByText('Awaiting review', { exact: true }).waitFor()
    await capture(page, 'cancellation-pending')
    const admin = await request('/auth/login', { email: 'admin@ferrovia.local', password: 'Admin123!' })
    const passengerBookings = await request('/bookings/mine', null, passenger.token, 'GET')
    const adminContext = await browser.newContext({ viewport: { width: 1440, height: 900 } })
    await adminContext.addInitScript(session => { localStorage.setItem('rail-token', session.token); localStorage.setItem('rail-user', JSON.stringify(session.user)) }, admin)
    const adminPage = await adminContext.newPage()
    await adminPage.goto(`${base}/?intro=0#/admin/cancellations`, { waitUntil: 'networkidle' })
    await adminPage.locator('.review-card').filter({hasText: passengerBookings[0].pnr_number}).getByRole('button', { name: 'Approve cancellation', exact: true }).click()
    await adminPage.getByRole('button', { name: 'Approve and cancel booking' }).click()
    await adminPage.getByText(/Cancellation approved/).waitFor()
    await adminContext.close()
    await page.reload({ waitUntil: 'networkidle' })
    await page.getByRole('tab', { name: /Cancelled/ }).click()
    await capture(page, 'tickets-cancelled')
    await page.getByRole('button', { name: 'View', exact: true }).click()
    await capture(page, 'refund-timeline')
    await page.keyboard.press('Escape')
    await page.goto(`${base}/?intro=0#/notifications`, { waitUntil: 'networkidle' })
    await capture(page, 'notifications-loaded')
    report.checks.push('Future booking cancellation, admin approval, refund timeline and notification')
    writeFileSync(resolve(out, 'report.json'), JSON.stringify(report, null, 2))
    assert.deepEqual(report.errors, [])
    assert.equal(report.screens.filter(s => s.overflow > 1).length, 0, 'Overflow: see report')
    assert.equal(report.screens.filter(s => s.violations.some(v => ['serious','critical'].includes(v.impact))).length, 0, 'Axe: see report')
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
