const assert = require('node:assert/strict')
const { chromium } = require('playwright-core')
const AxeBuilder = require('@axe-core/playwright').default
const { mkdirSync, writeFileSync, existsSync, readFileSync } = require('node:fs')
const { resolve } = require('node:path')
const { browserOptions } = require('./browser.cjs')
const base = 'http://localhost:5173/?intro=0'
const out = resolve(__dirname, '../artifacts/regression-audit')
mkdirSync(out, {recursive:true})
const report = process.env.AUDIT_RESUME && existsSync(resolve(out,'report.json')) ? JSON.parse(readFileSync(resolve(out,'report.json'))) : {checks:[],screens:[],errors:[]}
const save = () => writeFileSync(resolve(out,'report.json'),JSON.stringify(report,null,2))
const check = message => {if(!report.checks.includes(message))report.checks.push(message);save();console.log(message)}
async function api(path,body,token,method='POST') {
  const response = await fetch(`http://localhost:5000/api${path}`,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})})
  const data=await response.json();assert.ok(response.ok,JSON.stringify(data));return data.data
}
async function matrix(page,name,widths=[1440,1024,768,390,320]) {
  for(const theme of ['light','dark']) for(const width of widths) {
    const index=report.screens.findIndex(s=>s.name===name && s.theme===theme && s.width===width)
    if(process.env.AUDIT_RESUME && index>=0 && !report.screens[index].violations.length && report.screens[index].overflow<=0) continue
    if(index>=0) report.screens.splice(index,1)
    await page.setViewportSize({width,height:900})
    await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme)
    await page.waitForTimeout(750)
    const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)
    const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))
    await page.screenshot({path:resolve(out,`${name}-${theme}-${width}.png`),fullPage:true,animations:'disabled'})
    report.screens.push({name,theme,width,overflow,violations});save()
  }
  await page.setViewportSize({width:1440,height:900})
  check(`${name}: responsive and accessibility captures complete`)
}
async function main() {
  assert.equal((await api('/health',null,null,'GET')).databaseMode,'memory')
  const browser=await chromium.launch(browserOptions())
  try {
    async function newPage(session) {
      const context=await browser.newContext({viewport:{width:1440,height:900},timezoneId:'Asia/Dhaka'})
      if(session) await context.addInitScript(s=>{localStorage.setItem('rail-token',s.token);localStorage.setItem('rail-user',JSON.stringify(s.user))},session)
      const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));return page
    }
    const page=await newPage()
    await page.clock.install()
    await page.goto(base,{waitUntil:'networkidle'})
    await page.getByRole('button',{name:'Pause scenery',exact:true}).click()
    await page.locator('.hero-scene.is-idle').waitFor()
    await page.getByRole('button',{name:'Sign in',exact:true}).click()
    const dialog=page.getByRole('dialog')
    assert.equal(await dialog.evaluate(el=>getComputedStyle(el).opacity),'1')
    await matrix(page,'paused-signin')
    await page.keyboard.press('Escape')
    await page.reload({waitUntil:'networkidle'})
    assert.equal(await page.getByRole('button',{name:'Play scenery'}).getAttribute('aria-pressed'),'true')
    await page.getByRole('button',{name:'Play scenery'}).click()
    check('Motion pause persists and new dialogs remain visible')
    await page.getByPlaceholder('From where?').fill('Chattogram')
    await page.getByRole('option',{name:'Chattogram',exact:true}).click()
    await page.getByPlaceholder('To where?').fill('Dhaka')
    await page.getByRole('option',{name:'Dhaka',exact:true}).click()
    await page.getByRole('button',{name:'Search trains',exact:true}).click()
    await page.locator('.journey-card .fare-tile:not([disabled])').first().click()
    await page.locator('.seat:not([disabled])').first().click()
    await page.getByRole('button',{name:'Continue to passengers'}).click()
    await page.getByLabel('Full name',{exact:true}).fill('History Passenger')
    await page.goBack()
    await page.locator('.seat[aria-pressed=true]').waitFor()
    await page.goForward()
    assert.equal(await page.getByLabel('Full name',{exact:true}).inputValue(),'History Passenger')
    check('Booking browser back/forward preserves selected seats and passenger input')
    await page.reload({waitUntil:'networkidle'})
    await page.getByRole('heading',{name:'Anywhere to anywhere'}).waitFor()
    check('Reloading a booking deep link returns safely to search')
    await page.goto(`${base}#/track`,{waitUntil:'networkidle'})
    await page.getByRole('button',{name:'Track train',exact:true}).click()
    await page.getByRole('heading',{name:'Suborno Express'}).waitFor()
    await matrix(page,'tracking-result')
    await page.getByRole('combobox').fill('unfinished query')
    const refresh=page.waitForResponse(r=>/\/api\/trips\/\d+\/status/.test(r.url()))
    await page.clock.fastForward(61000)
    assert.ok((await refresh).ok())
    await page.getByRole('heading',{name:'Suborno Express'}).waitFor()
    await page.clock.resume()
    check('Automatic tracking refresh uses the displayed trip while search text is edited')
    await page.context().close()

    const admin=await api('/auth/login',{email:'admin@ferrovia.local',password:'Admin123!'})
    const adminPage=await newPage(admin)
    await adminPage.route('**/api/admin/train-services',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({success:false,error:'Test: service temporarily unavailable'})}))
    await adminPage.goto(`${base}#/admin`,{waitUntil:'networkidle'})
    await adminPage.getByText('Train services couldn’t load',{exact:true}).waitFor()
    assert.ok(await adminPage.locator('.departures-table tbody tr').count()>0)
    await matrix(adminPage,'admin-partial-error')
    await adminPage.unroute('**/api/admin/train-services')
    await adminPage.getByRole('button',{name:'Refresh',exact:true}).click()
    await adminPage.getByText('Train services couldn’t load',{exact:true}).waitFor({state:'hidden'})
    check('Admin partial failure retains departures; retry recovers')
    await adminPage.locator('.account-chip').click()
    assert.equal(await adminPage.evaluate(()=>document.activeElement.textContent.trim()),'Travel dashboard')
    await adminPage.keyboard.press('ArrowDown')
    assert.equal(await adminPage.evaluate(()=>document.activeElement.textContent.trim()),'My tickets')
    await matrix(adminPage,'account-menu',[1440,390,320])
    await adminPage.keyboard.press('Escape')
    assert.ok(await adminPage.locator('.account-chip').evaluate(el=>el===document.activeElement))
    await adminPage.getByRole('button',{name:/^Notifications/}).first().click()
    assert.ok(await adminPage.locator('.notif-menu').evaluate(el=>el.contains(document.activeElement)))
    await matrix(adminPage,'notification-popover',[1440,390,320])
    await adminPage.keyboard.press('Escape')
    check('Account arrow navigation and notification focus restoration')
    await adminPage.evaluate(()=>localStorage.removeItem('rail-token'))
    await adminPage.getByRole('button',{name:'Refresh',exact:true}).click()
    await adminPage.getByRole('button',{name:'Sign in',exact:true}).waitFor()
    await adminPage.getByText('Your session has ended. Sign in again to continue.').waitFor()
    check('Expired session resets user state and explains how to recover')
    await adminPage.context().close()

    const operator=await api('/auth/login',{email:'operator@ferrovia.local',password:'Operator123!'})
    const op=await newPage(operator)
    await op.goto(`${base}#/operator`,{waitUntil:'networkidle'})
    await op.locator('.op-trip').first().click()
    await op.locator('.op-stops-head').waitFor()
    await matrix(op,'operator-selected')
    const departed=op.getByRole('button',{name:'Departed',exact:true})
    if(await departed.count()) {
      await departed.first().click()
      await matrix(op,'operator-confirmation')
      await op.getByRole('dialog').getByRole('button',{name:'Record departure',exact:true}).click()
      await op.getByText(/spare.*reserved|Delay threshold triggered|departure recorded/).first().waitFor()
      check('Operator records departure with confirmation and spare-trainset feedback')
    }
    const arrived=op.getByRole('button',{name:'Arrived',exact:true})
    if(await arrived.count()) {
      await arrived.first().click()
      await op.getByRole('dialog').getByRole('button',{name:'Record arrival',exact:true}).click()
      await op.getByText(/arrival recorded/).first().waitFor()
      check('Operator records the next arrival')
    }
    await op.context().close()
    const reduced=await newPage()
    await reduced.emulateMedia({reducedMotion:'reduce'})
    await reduced.goto('http://localhost:5173/?intro=1',{waitUntil:'networkidle'})
    assert.equal(await reduced.locator('.intro').count(),0)
    assert.ok(await reduced.locator('.hero-scene.is-idle').count())
    check('Reduced motion overrides even a forced intro')
    await reduced.context().close()
    save()
    assert.deepEqual(report.errors,[])
    assert.equal(report.screens.filter(s=>s.overflow>1||s.violations.some(v=>['serious','critical'].includes(v.impact))).length,0,'See regression audit report')
  } finally {await browser.close()}
}
main().catch(e=>{save();console.error(e);process.exitCode=1})
