const assert=require('node:assert/strict')
const {chromium}=require('playwright-core')
const AxeBuilder=require('@axe-core/playwright').default
const {mkdirSync,writeFileSync,readFileSync,existsSync}=require('node:fs')
const {resolve}=require('node:path')
const {browserOptions}=require('./browser.cjs')
const out=resolve(__dirname,'../artifacts/state-audit');mkdirSync(out,{recursive:true})
const report=process.env.AUDIT_RESUME&&existsSync(resolve(out,'report.json'))?JSON.parse(readFileSync(resolve(out,'report.json'))):{checks:[],screens:[],errors:[]}
const save=()=>writeFileSync(resolve(out,'report.json'),JSON.stringify(report,null,2))
async function api(path,body,token,method='POST'){
 const r=await fetch('http://localhost:5000/api'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const p=await r.json();assert.ok(r.ok,JSON.stringify(p));return p.data
}
async function capture(page,name){
 for(const theme of ['light','dark'])for(const width of [1440,1024,768,390,320]){
  const index=report.screens.findIndex(s=>s.name===name&&s.theme===theme&&s.width===width)
  if(process.env.AUDIT_RESUME&&index>=0&&!report.screens[index].violations.length&&report.screens[index].overflow<=0)continue
  if(index>=0)report.screens.splice(index,1)
  await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.waitForTimeout(750)
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)
  const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))
  await page.screenshot({path:resolve(out,`${name}-${theme}-${width}.png`),fullPage:true,animations:'disabled'})
  report.screens.push({name,theme,width,overflow,violations});save()
 }
 await page.setViewportSize({width:1440,height:900});console.log(name,'captured')
}
async function main(){
 assert.equal((await api('/health',null,null,'GET')).databaseMode,'memory')
 const browser=await chromium.launch(browserOptions())
 try{
  const c=await browser.newContext({viewport:{width:1440,height:900},timezoneId:'Asia/Dhaka'}),p=await c.newPage()
  p.on('pageerror',e=>report.errors.push(e.message))
  await p.goto('http://localhost:5173/?intro=0#/support',{waitUntil:'networkidle'})
  await p.getByLabel('Search help articles').fill('no-matching-question-123')
  await p.getByPlaceholder('Your name').fill('Support Audit');await p.getByPlaceholder('you@example.com').fill('support.audit@example.com')
  await p.getByPlaceholder('How can we help?').fill('Please review booking PNR TEST-NOTE.')
  await capture(p,'support-no-results')
  const download=p.waitForEvent('download');await p.getByRole('button',{name:'Download note'}).click()
  const file=resolve(out,'support-note.txt');await (await download).saveAs(file)
  assert.ok(readFileSync(file,'utf8').includes('PNR TEST-NOTE'))
  assert.equal(await p.getByPlaceholder('How can we help?').inputValue(),'Please review booking PNR TEST-NOTE.')
  report.checks.push('Support note downloads its actual form contents without falsely claiming delivery')
  await p.getByRole('button',{name:'Open Conduttore assistant'}).click()
  let releaseChat;const gateChat=new Promise(r=>releaseChat=r)
  await p.route('**/api/chat',async route=>{await gateChat;await route.continue()})
  await p.getByLabel('Message Conduttore').fill('Suborno Express live status')
  await p.getByRole('button',{name:'Send message',exact:true}).click();await p.locator('.is-typing').waitFor()
  await capture(p,'assistant-typing');releaseChat()
  await p.locator('.is-typing').waitFor({state:'hidden'});await p.unroute('**/api/chat')
  assert.ok(await p.locator('.assistant-msg.is-assistant').count()>1)
  await capture(p,'assistant-answer')
  await p.route('**/api/chat',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Test: assistant temporarily unavailable'})}))
  await p.getByLabel('Message Conduttore').fill('Test service failure');await p.getByRole('button',{name:'Send message',exact:true}).click()
  await p.locator('.assistant-msg.is-error').waitFor();await capture(p,'assistant-error');await p.unroute('**/api/chat')
  await p.keyboard.press('Escape');report.checks.push('Assistant typing, database answer, service error and Escape close')
  await p.goto('http://localhost:5173/?intro=0',{waitUntil:'networkidle'})
  await p.getByPlaceholder('From where?').fill('Chattogram');await p.getByRole('option',{name:'Chattogram',exact:true}).click()
  await p.getByPlaceholder('To where?').fill('Dhaka');await p.getByRole('option',{name:'Dhaka',exact:true}).click()
  let releaseSearch;const gateSearch=new Promise(r=>releaseSearch=r)
  await p.route('**/api/trains/search**',async route=>{await gateSearch;await route.continue()})
  await p.getByRole('button',{name:'Search trains',exact:true}).click();await p.locator('.skeleton-journey').first().waitFor()
  await capture(p,'results-loading');releaseSearch()
  await p.locator('.journey-card').first().waitFor();await p.unroute('**/api/trains/search**')
  await p.locator('.filter-pill').filter({hasText:'Mail'}).click()
  await p.getByRole('heading',{name:'No trains match these filters'}).waitFor();await capture(p,'results-filtered-empty')
  await p.route('**/api/trains/search**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Test: timetable temporarily unavailable'})}))
  await p.getByRole('button',{name:'Change search'}).click();await p.locator('.search-box button[type=submit]').click()
  await p.getByText("We couldn't load trains for this route",{exact:true}).waitFor();await capture(p,'results-api-error')
  await p.unroute('**/api/trains/search**');report.checks.push('Search loading, filtered-empty and recoverable API-error states')
  await c.close()
  const admin=await api('/auth/login',{email:'admin@ferrovia.local',password:'Admin123!'})
  const operator=await api('/auth/login',{email:'operator@ferrovia.local',password:'Operator123!'})
  const trips=await api('/admin/trips',null,admin.token,'GET')
  const future=trips.find(t=>new Date(t.scheduled_departure).getTime()>Date.now())
  assert.ok(future,'A future memory trip is required')
  await api(`/admin/trips/${future.trip_id}/operator`,{operatorUserId:operator.user.user_id},admin.token,'PATCH')
  const oc=await browser.newContext({viewport:{width:1440,height:900},timezoneId:'America/Los_Angeles'})
  await oc.addInitScript(s=>{localStorage.setItem('rail-token',s.token);localStorage.setItem('rail-user',JSON.stringify(s.user))},operator)
  const op=await oc.newPage();op.on('pageerror',e=>report.errors.push(e.message))
  await op.goto('http://localhost:5173/?intro=0#/operator',{waitUntil:'networkidle'})
  await op.locator('.op-trip').filter({hasText:`#${future.trip_id}`}).click();await op.locator('.op-stops-head').waitFor()
  assert.equal(await op.getByRole('button',{name:/^Opens /}).first().isDisabled(),true)
  await capture(op,'operator-departure-locked')
  await op.getByRole('button',{name:'Operating date',exact:true}).click()
  await op.locator('.dp-grid button:not([disabled])').last().click()
  await op.getByRole('heading',{name:'No trips on this date'}).waitFor()
  assert.equal(await op.locator('.op-stops-head').count(),0)
  await capture(op,'operator-no-trips')
  report.checks.push('Departure lock, Dhaka calendar in a different browser timezone, and stale trip clearing on date change')
  await oc.close();save()
  assert.deepEqual(report.errors,[])
  assert.equal(report.screens.filter(s=>s.overflow>1||s.violations.some(v=>['serious','critical'].includes(v.impact))).length,0,'See state audit report')
 }finally{await browser.close()}
}
main().catch(e=>{save();console.error(e);process.exitCode=1})
