ALTER TABLE USERS DROP CONSTRAINT IF EXISTS CK_USERS_STATUS;

ALTER TABLE USERS
    ADD CONSTRAINT CK_USERS_STATUS
    CHECK (ACCOUNT_STATUS IN ('ACTIVE','PENDING','SUSPENDED','INACTIVE'));

CREATE INDEX IF NOT EXISTS IDX_USERS_PENDING_OPERATORS
    ON USERS (ACCOUNT_STATUS, CREATED_AT)
    WHERE ROLE = 'OPERATOR' AND ACCOUNT_STATUS = 'PENDING';
